### ISSUE TITLE
get_pointer should dereference tail pointer instead of self.tail.both

### ISSUE THREAD

**Issue by LihuaWu** [Jedshady/daily-coding-problem#1]
https://github.com/Jedshady/daily-coding-problem/blob/3f496ee09682d2faa79a44e6549401e871b23ce7/Problem%201-30/problem_6.py#L56

IMHO, it should be 
`element.both = get_pointer(prev) ^ get_pointer(self.tail)`

**Comment by Jedshady** [comment]
Hi Lihua,

Sorry for the late reply. I was pulled back by other things these days.
I had another look at the code. I think you are right. It should be self.tail.
Could you send a pull request? I'm happy to merge it in.

Thank you.
